services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 3000:80
    links:
      - php
    volumes:
      - ./packages/laravel:/var/www/laravel:cached

  php:
    build: ./docker/php/
    expose:
      - 9000
    links:
      - db
    volumes:
      - ./packages/laravel:/var/www/laravel:cached

  db:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:delegated
      - ./docker/db/entrypoint:/docker-entrypoint-initdb.d/
